server:
  port: 8002
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.230.44:3306/sxhdmy_service?serverTimezone=GMT%2B8
    username: root
    password: MyNewPass4!
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL

  cloud:
    nacos:
      discovery:
        server-addr: 139.196.166.75:8848
  application:
    name: sxdhmy-factory

  devtools:
    restart:
      enabled: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: com/oscars/factory/mapper/xml/*.xml


feign:
  hystrix:
    enabled: true
