server:
  port: 9527

spring:
  application:
    name: sxhd-gateway
  cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
      gateway:
#        globalcors:
#          cors-configurations:
#            '[/**]':
#              allowedOrigins: "*"
#              allowedMethods: "*"
#              allowedHeaders: "*"
        routes:
          - id: admin_router
            uri: lb://renren-fast
            predicates:
              - Path=/api/app/**
            filters:
              - StripPrefix=1
          - id: admin_router2
            uri: lb://renren-fast
            predicates:
              - Path=/api/sys/**
            filters:
              - StripPrefix=1
          - id: product_router
            uri: lb://sxdhmy-factory
            predicates:
              - Path=/api/admin/**
            filters:
              - StripPrefix=2
          - id: ofs_router
            uri: lb://service-ofs
            predicates:
              - Path=/api/ofs/**
            filters:
              - StripPrefix=2
          - id: admin_router3
            uri: lb://renren-fast
            predicates:
              - Path=/api/**
            filters:
              - StripPrefix=1


